export const Permissions = {
  // Financial
  FINANCIAL_INVOICES_CREATE: 'financial.invoices.create',
  FINANCIAL_INVOICES_VIEW: 'financial.invoices.view',
  FINANCIAL_INVOICES_SEND: 'financial.invoices.send',
  FINANCIAL_INVOICES_VOID: 'financial.invoices.void',
  FINANCIAL_PAYMENTS_VIEW: 'financial.payments.view',
  FINANCIAL_PAYMENTS_LOG: 'financial.payments.log',
  FINANCIAL_REPORTS_VIEW: 'financial.reports.view',
  FINANCIAL_GL_VIEW: 'financial.gl.view',
  FINANCIAL_GL_MANAGE: 'financial.gl.manage',
  FINANCIAL_JOURNAL_CREATE: 'financial.journal.create',
  FINANCIAL_JOURNAL_VIEW: 'financial.journal.view',
  FINANCIAL_RECONCILIATION_MANAGE: 'financial.reconciliation.manage',

  // Management
  MANAGEMENT_ESTATES_VIEW: 'management.estates.view',
  MANAGEMENT_ESTATES_MANAGE: 'management.estates.manage',
  MANAGEMENT_UNITS_VIEW: 'management.units.view',
  MANAGEMENT_UNITS_MANAGE: 'management.units.manage',
  MANAGEMENT_PEOPLE_VIEW: 'management.people.view',
  MANAGEMENT_PEOPLE_MANAGE: 'management.people.manage',
  MANAGEMENT_VIOLATIONS_CREATE: 'management.violations.create',
  MANAGEMENT_VIOLATIONS_VIEW: 'management.violations.view',
  MANAGEMENT_REQUESTS_VIEW: 'management.requests.view',
  MANAGEMENT_REQUESTS_MANAGE: 'management.requests.manage',
  MANAGEMENT_DOCUMENTS_VIEW: 'management.documents.view',
  MANAGEMENT_DOCUMENTS_MANAGE: 'management.documents.manage',

  // Communications
  COMMUNICATIONS_BROADCAST_SEND: 'communications.broadcast.send',
  COMMUNICATIONS_BROADCAST_VIEW: 'communications.broadcast.view',

  // Visitors
  VISITORS_PASSES_CREATE: 'visitors.passes.create',
  VISITORS_PASSES_VIEW: 'visitors.passes.view',
  VISITORS_PASSES_VERIFY: 'visitors.passes.verify',

  // Admin
  ADMIN_USERS_INVITE: 'admin.users.invite',
  ADMIN_USERS_MANAGE: 'admin.users.manage',
  ADMIN_ROLES_MANAGE: 'admin.roles.manage',
  ADMIN_ORG_SETTINGS: 'admin.org.settings',
  ADMIN_AUDIT_VIEW: 'admin.audit.view',
} as const;

export type Permission = (typeof Permissions)[keyof typeof Permissions];

export const RolePermissions: Record<string, Permission[]> = {
  super_admin: Object.values(Permissions),
  hoa_admin: Object.values(Permissions),
  property_manager: [
    Permissions.MANAGEMENT_ESTATES_VIEW,
    Permissions.MANAGEMENT_ESTATES_MANAGE,
    Permissions.MANAGEMENT_UNITS_VIEW,
    Permissions.MANAGEMENT_UNITS_MANAGE,
    Permissions.MANAGEMENT_PEOPLE_VIEW,
    Permissions.MANAGEMENT_PEOPLE_MANAGE,
    Permissions.MANAGEMENT_VIOLATIONS_CREATE,
    Permissions.MANAGEMENT_VIOLATIONS_VIEW,
    Permissions.MANAGEMENT_REQUESTS_VIEW,
    Permissions.MANAGEMENT_REQUESTS_MANAGE,
    Permissions.MANAGEMENT_DOCUMENTS_VIEW,
    Permissions.MANAGEMENT_DOCUMENTS_MANAGE,
    Permissions.FINANCIAL_INVOICES_VIEW,
    Permissions.FINANCIAL_INVOICES_CREATE,
    Permissions.FINANCIAL_INVOICES_SEND,
    Permissions.FINANCIAL_PAYMENTS_VIEW,
    Permissions.FINANCIAL_REPORTS_VIEW,
    Permissions.COMMUNICATIONS_BROADCAST_SEND,
    Permissions.COMMUNICATIONS_BROADCAST_VIEW,
    Permissions.VISITORS_PASSES_VIEW,
    Permissions.VISITORS_PASSES_VERIFY,
  ],
  finance_officer: [
    Permissions.FINANCIAL_INVOICES_CREATE,
    Permissions.FINANCIAL_INVOICES_VIEW,
    Permissions.FINANCIAL_INVOICES_SEND,
    Permissions.FINANCIAL_INVOICES_VOID,
    Permissions.FINANCIAL_PAYMENTS_VIEW,
    Permissions.FINANCIAL_PAYMENTS_LOG,
    Permissions.FINANCIAL_REPORTS_VIEW,
    Permissions.FINANCIAL_GL_VIEW,
    Permissions.FINANCIAL_GL_MANAGE,
    Permissions.FINANCIAL_JOURNAL_CREATE,
    Permissions.FINANCIAL_JOURNAL_VIEW,
    Permissions.FINANCIAL_RECONCILIATION_MANAGE,
  ],
  exco_member: [
    Permissions.FINANCIAL_INVOICES_VIEW,
    Permissions.FINANCIAL_PAYMENTS_VIEW,
    Permissions.FINANCIAL_REPORTS_VIEW,
    Permissions.FINANCIAL_GL_VIEW,
    Permissions.FINANCIAL_JOURNAL_VIEW,
    Permissions.MANAGEMENT_ESTATES_VIEW,
    Permissions.MANAGEMENT_UNITS_VIEW,
    Permissions.MANAGEMENT_PEOPLE_VIEW,
    Permissions.MANAGEMENT_VIOLATIONS_VIEW,
    Permissions.MANAGEMENT_REQUESTS_VIEW,
    Permissions.MANAGEMENT_DOCUMENTS_VIEW,
    Permissions.COMMUNICATIONS_BROADCAST_VIEW,
    Permissions.ADMIN_AUDIT_VIEW,
  ],
  owner: [
    Permissions.FINANCIAL_INVOICES_VIEW,
    Permissions.FINANCIAL_PAYMENTS_VIEW,
    Permissions.MANAGEMENT_DOCUMENTS_VIEW,
    Permissions.MANAGEMENT_REQUESTS_VIEW,
    Permissions.VISITORS_PASSES_CREATE,
    Permissions.VISITORS_PASSES_VIEW,
  ],
  tenant: [
    Permissions.FINANCIAL_INVOICES_VIEW,
    Permissions.FINANCIAL_PAYMENTS_VIEW,
    Permissions.MANAGEMENT_DOCUMENTS_VIEW,
    Permissions.MANAGEMENT_REQUESTS_VIEW,
    Permissions.VISITORS_PASSES_CREATE,
    Permissions.VISITORS_PASSES_VIEW,
  ],
};
